const Types = {
  SIGN_IN_STARTED: 'SIGN_IN_STARTED',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'SIGN_IN_FAILED',
  SIGN_UP_STARTED: 'SIGN_IN_STARTED',
  SIGN_UP_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_UP_FAILED: 'SIGN_IN_FAILED',
}

export default Types
